<?php

namespace Database\Seeders;

use App\Models\Settings\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SeederCountry extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("countries")->truncate();
        $countries = array(
            'AF' => array(
                'country_name' => 'Afghanistan',
                'phone_code' => 93,
                'id' => 1,
                'continent_code' => 'AS',
                'continent_name' => 'Asia'),
            'AX' => array('country_name' => 'Aland Islands','phone_code' => 358,'id' => 2,'continent_code' => 'EU','continent_name' => 'Europe'),
            'AL' => array('country_name' => 'Albania','phone_code' => 355,'id' => 3,'continent_code' => 'EU','continent_name' => 'Europe'),
            'DZ' => array('country_name' => 'Algeria','phone_code' => 213,'id' => 4,'continent_code' => 'AF','continent_name' => 'Africa'),
            'AS' => array('country_name' => 'American Samoa','phone_code' => 1684,'id' => 5,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'AD' => array('country_name' => 'Andorra','phone_code' => 376,'id' => 6,'continent_code' => 'EU','continent_name' => 'Europe'),
            'AO' => array('country_name' => 'Angola','phone_code' => 244,'id' => 7,'continent_code' => 'AF','continent_name' => 'Africa'),
            'AI' => array('country_name' => 'Anguilla','phone_code' => 1264,'id' => 8,'continent_code' => 'NA','continent_name' => 'North America'),
            'AQ' => array('country_name' => 'Antarctica','phone_code' => 672,'id' => 9,'continent_code' => 'AN','continent_name' => 'Antarctica'),
            'AG' => array('country_name' => 'Antigua and Barbuda','phone_code' => 1268,'id' => 10,'continent_code' => 'NA','continent_name' => 'North America'),
            'AR' => array('country_name' => 'Argentina','phone_code' => 54,'id' => 11,'continent_code' => 'SA','continent_name' => 'South America'),
            'AM' => array('country_name' => 'Armenia','phone_code' => 374,'id' => 12,'continent_code' => 'AS','continent_name' => 'Asia'),
            'AW' => array('country_name' => 'Aruba','phone_code' => 297,'id' => 13,'continent_code' => 'NA','continent_name' => 'North America'),
            'AU' => array('country_name' => 'Australia','phone_code' => 61,'id' => 14,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'AT' => array('country_name' => 'Austria','phone_code' => 43,'id' => 15,'continent_code' => 'EU','continent_name' => 'Europe'),
            'AZ' => array('country_name' => 'Azerbaijan','phone_code' => 994,'id' => 16,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BS' => array('country_name' => 'Bahamas','phone_code' => 1242,'id' => 17,'continent_code' => 'NA','continent_name' => 'North America'),
            'BH' => array('country_name' => 'Bahrain','phone_code' => 973,'id' => 18,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BD' => array('country_name' => 'Bangladesh','phone_code' => 880,'id' => 19,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BB' => array('country_name' => 'Barbados','phone_code' => 1246,'id' => 20,'continent_code' => 'NA','continent_name' => 'North America'),
            'BY' => array('country_name' => 'Belarus','phone_code' => 375,'id' => 21,'continent_code' => 'EU','continent_name' => 'Europe'),
            'BE' => array('country_name' => 'Belgium','phone_code' => 32,'id' => 22,'continent_code' => 'EU','continent_name' => 'Europe'),
            'BZ' => array('country_name' => 'Belize','phone_code' => 501,'id' => 23,'continent_code' => 'NA','continent_name' => 'North America'),
            'BJ' => array('country_name' => 'Benin','phone_code' => 229,'id' => 24,'continent_code' => 'AF','continent_name' => 'Africa'),
            'BM' => array('country_name' => 'Bermuda','phone_code' => 1441,'id' => 25,'continent_code' => 'NA','continent_name' => 'North America'),
            'BT' => array('country_name' => 'Bhutan','phone_code' => 975,'id' => 26,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BO' => array('country_name' => 'Bolivia','phone_code' => 591,'id' => 27,'continent_code' => 'SA','continent_name' => 'South America'),
            'BQ' => array('country_name' => 'Bonaire, Sint Eustatius and Saba','phone_code' => 599,'id' => 28,'continent_code' => 'NA','continent_name' => 'North America'),
            'BA' => array('country_name' => 'Bosnia and Herzegovina','phone_code' => 387,'id' => 29,'continent_code' => 'EU','continent_name' => 'Europe'),
            'BW' => array('country_name' => 'Botswana','phone_code' => 267,'id' => 30,'continent_code' => 'AF','continent_name' => 'Africa'),
            'BV' => array('country_name' => 'Bouvet Island','phone_code' => 55,'id' => 31,'continent_code' => 'AN','continent_name' => 'Antarctica'),
            'BR' => array('country_name' => 'Brazil','phone_code' => 55,'id' => 32,'continent_code' => 'SA','continent_name' => 'South America'),
            'IO' => array('country_name' => 'British Indian Ocean Territory','phone_code' => 246,'id' => 33,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BN' => array('country_name' => 'Brunei Darussalam','phone_code' => 673,'id' => 34,'continent_code' => 'AS','continent_name' => 'Asia'),
            'BG' => array('country_name' => 'Bulgaria','phone_code' => 359,'id' => 35,'continent_code' => 'EU','continent_name' => 'Europe'),
            'BF' => array('country_name' => 'Burkina Faso','phone_code' => 226,'id' => 36,'continent_code' => 'AF','continent_name' => 'Africa'),
            'BI' => array('country_name' => 'Burundi','phone_code' => 257,'id' => 37,'continent_code' => 'AF','continent_name' => 'Africa'),
            'KH' => array('country_name' => 'Cambodia','phone_code' => 855,'id' => 38,'continent_code' => 'AS','continent_name' => 'Asia'),
            'CM' => array('country_name' => 'Cameroon','phone_code' => 237,'id' => 39,'continent_code' => 'AF','continent_name' => 'Africa'),
            'CA' => array('country_name' => 'Canada','phone_code' => 1,'id' => 40,'continent_code' => 'NA','continent_name' => 'North America'),
            'CV' => array('country_name' => 'Cape Verde','phone_code' => 238,'id' => 41,'continent_code' => 'AF','continent_name' => 'Africa'),
            'KY' => array('country_name' => 'Cayman Islands','phone_code' => 1345,'id' => 42,'continent_code' => 'NA','continent_name' => 'North America'),
            'CF' => array('country_name' => 'Central African Republic','phone_code' => 236,'id' => 43,'continent_code' => 'AF','continent_name' => 'Africa'),
            'TD' => array('country_name' => 'Chad','phone_code' => 235,'id' => 44,'continent_code' => 'AF','continent_name' => 'Africa'),
            'CL' => array('country_name' => 'Chile','phone_code' => 56,'id' => 45,'continent_code' => 'SA','continent_name' => 'South America'),
            'CN' => array('country_name' => 'China','phone_code' => 86,'id' => 46,'continent_code' => 'AS','continent_name' => 'Asia'),
            'CX' => array('country_name' => 'Christmas Island','phone_code' => 61,'id' => 47,'continent_code' => 'AS','continent_name' => 'Asia'),
            'CC' => array('country_name' => 'Cocos (Keeling) Islands','phone_code' => 672,'id' => 48,'continent_code' => 'AS','continent_name' => 'Asia'),
            'CO' => array('country_name' => 'Colombia','phone_code' => 57,'id' => 49,'continent_code' => 'SA','continent_name' => 'South America'),
            'KM' => array('country_name' => 'Comoros','phone_code' => 269,'id' => 50,'continent_code' => 'AF','continent_name' => 'Africa'),
            'CG' => array('country_name' => 'Congo','phone_code' => 242,'id' => 51,'continent_code' => 'AF','continent_name' => 'Africa'),
            'CD' => array('country_name' => 'Congo, Democratic Republic of the Congo','phone_code' => 242,'id' => 52,'continent_code' => 'AF','continent_name' => 'Africa'),
            'CK' => array('country_name' => 'Cook Islands','phone_code' => 682,'id' => 53,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'CR' => array('country_name' => 'Costa Rica','phone_code' => 506,'id' => 54,'continent_code' => 'NA','continent_name' => 'North America'),
            'CI' => array('country_name' => 'Cote D\'Ivoire','phone_code' => 225,'id' => 55,'continent_code' => 'AF','continent_name' => 'Africa'),
            'HR' => array('country_name' => 'Croatia','phone_code' => 385,'id' => 56,'continent_code' => 'EU','continent_name' => 'Europe'),
            'CU' => array('country_name' => 'Cuba','phone_code' => 53,'id' => 57,'continent_code' => 'NA','continent_name' => 'North America'),
            'CW' => array('country_name' => 'Curacao','phone_code' => 599,'id' => 58,'continent_code' => 'NA','continent_name' => 'North America'),
            'CY' => array('country_name' => 'Cyprus','phone_code' => 357,'id' => 59,'continent_code' => 'AS','continent_name' => 'Asia'),
            'CZ' => array('country_name' => 'Czech Republic','phone_code' => 420,'id' => 60,'continent_code' => 'EU','continent_name' => 'Europe'),
            'DK' => array('country_name' => 'Denmark','phone_code' => 45,'id' => 61,'continent_code' => 'EU','continent_name' => 'Europe'),
            'DJ' => array('country_name' => 'Djibouti','phone_code' => 253,'id' => 62,'continent_code' => 'AF','continent_name' => 'Africa'),
            'DM' => array('country_name' => 'Dominica','phone_code' => 1767,'id' => 63,'continent_code' => 'NA','continent_name' => 'North America'),
            'DO' => array('country_name' => 'Dominican Republic','phone_code' => 1809,'id' => 64,'continent_code' => 'NA','continent_name' => 'North America'),
            'EC' => array('country_name' => 'Ecuador','phone_code' => 593,'id' => 65,'continent_code' => 'SA','continent_name' => 'South America'),
            'EG' => array('country_name' => 'Egypt','phone_code' => 20,'id' => 66,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SV' => array('country_name' => 'El Salvador','phone_code' => 503,'id' => 67,'continent_code' => 'NA','continent_name' => 'North America'),
            'GQ' => array('country_name' => 'Equatorial Guinea','phone_code' => 240,'id' => 68,'continent_code' => 'AF','continent_name' => 'Africa'),
            'ER' => array('country_name' => 'Eritrea','phone_code' => 291,'id' => 69,'continent_code' => 'AF','continent_name' => 'Africa'),
            'EE' => array('country_name' => 'Estonia','phone_code' => 372,'id' => 70,'continent_code' => 'EU','continent_name' => 'Europe'),
            'ET' => array('country_name' => 'Ethiopia','phone_code' => 251,'id' => 71,'continent_code' => 'AF','continent_name' => 'Africa'),
            'FK' => array('country_name' => 'Falkland Islands (Malvinas)','phone_code' => 500,'id' => 72,'continent_code' => 'SA','continent_name' => 'South America'),
            'FO' => array('country_name' => 'Faroe Islands','phone_code' => 298,'id' => 73,'continent_code' => 'EU','continent_name' => 'Europe'),
            'FJ' => array('country_name' => 'Fiji','phone_code' => 679,'id' => 74,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'FI' => array('country_name' => 'Finland','phone_code' => 358,'id' => 75,'continent_code' => 'EU','continent_name' => 'Europe'),
            'FR' => array('country_name' => 'France','phone_code' => 33,'id' => 76,'continent_code' => 'EU','continent_name' => 'Europe'),
            'GF' => array('country_name' => 'French Guiana','phone_code' => 594,'id' => 77,'continent_code' => 'SA','continent_name' => 'South America'),
            'PF' => array('country_name' => 'French Polynesia','phone_code' => 689,'id' => 78,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'TF' => array('country_name' => 'French Southern Territories','phone_code' => 262,'id' => 79,'continent_code' => 'AN','continent_name' => 'Antarctica'),
            'GA' => array('country_name' => 'Gabon','phone_code' => 241,'id' => 80,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GM' => array('country_name' => 'Gambia','phone_code' => 220,'id' => 81,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GE' => array('country_name' => 'Georgia','phone_code' => 995,'id' => 82,'continent_code' => 'AS','continent_name' => 'Asia'),
            'DE' => array('country_name' => 'Germany','phone_code' => 49,'id' => 83,'continent_code' => 'EU','continent_name' => 'Europe'),
            'GH' => array('country_name' => 'Ghana','phone_code' => 233,'id' => 84,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GI' => array('country_name' => 'Gibraltar','phone_code' => 350,'id' => 85,'continent_code' => 'EU','continent_name' => 'Europe'),
            'GR' => array('country_name' => 'Greece','phone_code' => 30,'id' => 86,'continent_code' => 'EU','continent_name' => 'Europe'),
            'GL' => array('country_name' => 'Greenland','phone_code' => 299,'id' => 87,'continent_code' => 'NA','continent_name' => 'North America'),
            'GD' => array('country_name' => 'Grenada','phone_code' => 1473,'id' => 88,'continent_code' => 'NA','continent_name' => 'North America'),
            'GP' => array('country_name' => 'Guadeloupe','phone_code' => 590,'id' => 89,'continent_code' => 'NA','continent_name' => 'North America'),
            'GU' => array('country_name' => 'Guam','phone_code' => 1671,'id' => 90,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'GT' => array('country_name' => 'Guatemala','phone_code' => 502,'id' => 91,'continent_code' => 'NA','continent_name' => 'North America'),
            'GG' => array('country_name' => 'Guernsey','phone_code' => 44,'id' => 92,'continent_code' => 'EU','continent_name' => 'Europe'),
            'GN' => array('country_name' => 'Guinea','phone_code' => 224,'id' => 93,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GW' => array('country_name' => 'Guinea-Bissau','phone_code' => 245,'id' => 94,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GY' => array('country_name' => 'Guyana','phone_code' => 592,'id' => 95,'continent_code' => 'SA','continent_name' => 'South America'),
            'HT' => array('country_name' => 'Haiti','phone_code' => 509,'id' => 96,'continent_code' => 'NA','continent_name' => 'North America'),
            'HM' => array('country_name' => 'Heard Island and Mcdonald Islands','phone_code' => 0,'id' => 97,'continent_code' => 'AN','continent_name' => 'Antarctica'),
            'VA' => array('country_name' => 'Holy See (Vatican City State)','phone_code' => 39,'id' => 98,'continent_code' => 'EU','continent_name' => 'Europe'),
            'HN' => array('country_name' => 'Honduras','phone_code' => 504,'id' => 99,'continent_code' => 'NA','continent_name' => 'North America'),
            'HK' => array('country_name' => 'Hong Kong','phone_code' => 852,'id' => 100,'continent_code' => 'AS','continent_name' => 'Asia'),
            'HU' => array('country_name' => 'Hungary','phone_code' => 36,'id' => 101,'continent_code' => 'EU','continent_name' => 'Europe'),
            'IS' => array('country_name' => 'Iceland','phone_code' => 354,'id' => 102,'continent_code' => 'EU','continent_name' => 'Europe'),
            'IN' => array('country_name' => 'India','phone_code' => 91,'id' => 103,'continent_code' => 'AS','continent_name' => 'Asia'),
            'ID' => array('country_name' => 'Indonesia','phone_code' => 62,'id' => 104,'continent_code' => 'AS','continent_name' => 'Asia'),
            'IR' => array('country_name' => 'Iran, Islamic Republic of','phone_code' => 98,'id' => 105,'continent_code' => 'AS','continent_name' => 'Asia'),
            'IQ' => array('country_name' => 'Iraq','phone_code' => 964,'id' => 106,'continent_code' => 'AS','continent_name' => 'Asia'),
            'IE' => array('country_name' => 'Ireland','phone_code' => 353,'id' => 107,'continent_code' => 'EU','continent_name' => 'Europe'),
            'IM' => array('country_name' => 'Isle of Man','phone_code' => 44,'id' => 108,'continent_code' => 'EU','continent_name' => 'Europe'),
            'IL' => array('country_name' => 'Israel','phone_code' => 972,'id' => 109,'continent_code' => 'AS','continent_name' => 'Asia'),
            'IT' => array('country_name' => 'Italy','phone_code' => 39,'id' => 110,'continent_code' => 'EU','continent_name' => 'Europe'),
            'JM' => array('country_name' => 'Jamaica','phone_code' => 1876,'id' => 111,'continent_code' => 'NA','continent_name' => 'North America'),
            'JP' => array('country_name' => 'Japan','phone_code' => 81,'id' => 112,'continent_code' => 'AS','continent_name' => 'Asia'),
            'JE' => array('country_name' => 'Jersey','phone_code' => 44,'id' => 113,'continent_code' => 'EU','continent_name' => 'Europe'),
            'JO' => array('country_name' => 'Jordan','phone_code' => 962,'id' => 114,'continent_code' => 'AS','continent_name' => 'Asia'),
            'KZ' => array('country_name' => 'Kazakhstan','phone_code' => 7,'id' => 115,'continent_code' => 'AS','continent_name' => 'Asia'),
            'KE' => array('country_name' => 'Kenya','phone_code' => 254,'id' => 116,'continent_code' => 'AF','continent_name' => 'Africa'),
            'KI' => array('country_name' => 'Kiribati','phone_code' => 686,'id' => 117,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'KP' => array('country_name' => 'Korea, Democratic People\'s Republic of','phone_code' => 850,'id' => 118,'continent_code' => 'AS','continent_name' => 'Asia'),
            'KR' => array('country_name' => 'Korea, Republic of','phone_code' => 82,'id' => 119,'continent_code' => 'AS','continent_name' => 'Asia'),
            'XK' => array('country_name' => 'Kosovo','phone_code' => 381,'id' => 120,'continent_code' => 'EU','continent_name' => 'Europe'),
            'KW' => array('country_name' => 'Kuwait','phone_code' => 965,'id' => 121,'continent_code' => 'AS','continent_name' => 'Asia'),
            'KG' => array('country_name' => 'Kyrgyzstan','phone_code' => 996,'id' => 122,'continent_code' => 'AS','continent_name' => 'Asia'),
            'LA' => array('country_name' => 'Lao People\'s Democratic Republic','phone_code' => 856,'id' => 123,'continent_code' => 'AS','continent_name' => 'Asia'),
            'LV' => array('country_name' => 'Latvia','phone_code' => 371,'id' => 124,'continent_code' => 'EU','continent_name' => 'Europe'),
            'LB' => array('country_name' => 'Lebanon','phone_code' => 961,'id' => 125,'continent_code' => 'AS','continent_name' => 'Asia'),
            'LS' => array('country_name' => 'Lesotho','phone_code' => 266,'id' => 126,'continent_code' => 'AF','continent_name' => 'Africa'),
            'LR' => array('country_name' => 'Liberia','phone_code' => 231,'id' => 127,'continent_code' => 'AF','continent_name' => 'Africa'),
            'LY' => array('country_name' => 'Libyan Arab Jamahiriya','phone_code' => 218,'id' => 128,'continent_code' => 'AF','continent_name' => 'Africa'),
            'LI' => array('country_name' => 'Liechtenstein','phone_code' => 423,'id' => 129,'continent_code' => 'EU','continent_name' => 'Europe'),
            'LT' => array('country_name' => 'Lithuania','phone_code' => 370,'id' => 130,'continent_code' => 'EU','continent_name' => 'Europe'),
            'LU' => array('country_name' => 'Luxembourg','phone_code' => 352,'id' => 131,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MO' => array('country_name' => 'Macao','phone_code' => 853,'id' => 132,'continent_code' => 'AS','continent_name' => 'Asia'),
            'MK' => array('country_name' => 'Macedonia, the Former Yugoslav Republic of','phone_code' => 389,'id' => 133,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MG' => array('country_name' => 'Madagascar','phone_code' => 261,'id' => 134,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MW' => array('country_name' => 'Malawi','phone_code' => 265,'id' => 135,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MY' => array('country_name' => 'Malaysia','phone_code' => 60,'id' => 136,'continent_code' => 'AS','continent_name' => 'Asia'),
            'MV' => array('country_name' => 'Maldives','phone_code' => 960,'id' => 137,'continent_code' => 'AS','continent_name' => 'Asia'),
            'ML' => array('country_name' => 'Mali','phone_code' => 223,'id' => 138,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MT' => array('country_name' => 'Malta','phone_code' => 356,'id' => 139,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MH' => array('country_name' => 'Marshall Islands','phone_code' => 692,'id' => 140,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'MQ' => array('country_name' => 'Martinique','phone_code' => 596,'id' => 141,'continent_code' => 'NA','continent_name' => 'North America'),
            'MR' => array('country_name' => 'Mauritania','phone_code' => 222,'id' => 142,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MU' => array('country_name' => 'Mauritius','phone_code' => 230,'id' => 143,'continent_code' => 'AF','continent_name' => 'Africa'),
            'YT' => array('country_name' => 'Mayotte','phone_code' => 269,'id' => 144,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MX' => array('country_name' => 'Mexico','phone_code' => 52,'id' => 145,'continent_code' => 'NA','continent_name' => 'North America'),
            'FM' => array('country_name' => 'Micronesia, Federated States of','phone_code' => 691,'id' => 146,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'MD' => array('country_name' => 'Moldova, Republic of','phone_code' => 373,'id' => 147,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MC' => array('country_name' => 'Monaco','phone_code' => 377,'id' => 148,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MN' => array('country_name' => 'Mongolia','phone_code' => 976,'id' => 149,'continent_code' => 'AS','continent_name' => 'Asia'),
            'ME' => array('country_name' => 'Montenegro','phone_code' => 382,'id' => 150,'continent_code' => 'EU','continent_name' => 'Europe'),
            'MS' => array('country_name' => 'Montserrat','phone_code' => 1664,'id' => 151,'continent_code' => 'NA','continent_name' => 'North America'),
            'MA' => array('country_name' => 'Morocco','phone_code' => 212,'id' => 152,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MZ' => array('country_name' => 'Mozambique','phone_code' => 258,'id' => 153,'continent_code' => 'AF','continent_name' => 'Africa'),
            'MM' => array('country_name' => 'Myanmar','phone_code' => 95,'id' => 154,'continent_code' => 'AS','continent_name' => 'Asia'),
            'NA' => array('country_name' => 'Namibia','phone_code' => 264,'id' => 155,'continent_code' => 'AF','continent_name' => 'Africa'),
            'NR' => array('country_name' => 'Nauru','phone_code' => 674,'id' => 156,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'NP' => array('country_name' => 'Nepal','phone_code' => 977,'id' => 157,'continent_code' => 'AS','continent_name' => 'Asia'),
            'NL' => array('country_name' => 'Netherlands','phone_code' => 31,'id' => 158,'continent_code' => 'EU','continent_name' => 'Europe'),
            'AN' => array('country_name' => 'Netherlands Antilles','phone_code' => 599,'id' => 159,'continent_code' => 'NA','continent_name' => 'North America'),
            'NC' => array('country_name' => 'New Caledonia','phone_code' => 687,'id' => 160,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'NZ' => array('country_name' => 'New Zealand','phone_code' => 64,'id' => 161,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'NI' => array('country_name' => 'Nicaragua','phone_code' => 505,'id' => 162,'continent_code' => 'NA','continent_name' => 'North America'),
            'NE' => array('country_name' => 'Niger','phone_code' => 227,'id' => 163,'continent_code' => 'AF','continent_name' => 'Africa'),
            'NG' => array('country_name' => 'Nigeria','phone_code' => 234,'id' => 164,'continent_code' => 'AF','continent_name' => 'Africa'),
            'NU' => array('country_name' => 'Niue','phone_code' => 683,'id' => 165,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'NF' => array('country_name' => 'Norfolk Island','phone_code' => 672,'id' => 166,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'MP' => array('country_name' => 'Northern Mariana Islands','phone_code' => 1670,'id' => 167,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'NO' => array('country_name' => 'Norway','phone_code' => 47,'id' => 168,'continent_code' => 'EU','continent_name' => 'Europe'),
            'OM' => array('country_name' => 'Oman','phone_code' => 968,'id' => 169,'continent_code' => 'AS','continent_name' => 'Asia'),
            'PK' => array('country_name' => 'Pakistan','phone_code' => 92,'id' => 170,'continent_code' => 'AS','continent_name' => 'Asia'),
            'PW' => array('country_name' => 'Palau','phone_code' => 680,'id' => 171,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'PS' => array('country_name' => 'Palestinian Territory, Occupied','phone_code' => 970,'id' => 172,'continent_code' => 'AS','continent_name' => 'Asia'),
            'PA' => array('country_name' => 'Panama','phone_code' => 507,'id' => 173,'continent_code' => 'NA','continent_name' => 'North America'),
            'PG' => array('country_name' => 'Papua New Guinea','phone_code' => 675,'id' => 174,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'PY' => array('country_name' => 'Paraguay','phone_code' => 595,'id' => 175,'continent_code' => 'SA','continent_name' => 'South America'),
            'PE' => array('country_name' => 'Peru','phone_code' => 51,'id' => 176,'continent_code' => 'SA','continent_name' => 'South America'),
            'PH' => array('country_name' => 'Philippines','phone_code' => 63,'id' => 177,'continent_code' => 'AS','continent_name' => 'Asia'),
            'PN' => array('country_name' => 'Pitcairn','phone_code' => 64,'id' => 178,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'PL' => array('country_name' => 'Poland','phone_code' => 48,'id' => 179,'continent_code' => 'EU','continent_name' => 'Europe'),
            'PT' => array('country_name' => 'Portugal','phone_code' => 351,'id' => 180,'continent_code' => 'EU','continent_name' => 'Europe'),
            'PR' => array('country_name' => 'Puerto Rico','phone_code' => 1787,'id' => 181,'continent_code' => 'NA','continent_name' => 'North America'),
            'QA' => array('country_name' => 'Qatar','phone_code' => 974,'id' => 182,'continent_code' => 'AS','continent_name' => 'Asia'),
            'RE' => array('country_name' => 'Reunion','phone_code' => 262,'id' => 183,'continent_code' => 'AF','continent_name' => 'Africa'),
            'RO' => array('country_name' => 'Romania','phone_code' => 40,'id' => 184,'continent_code' => 'EU','continent_name' => 'Europe'),
            'RU' => array('country_name' => 'Russian Federation','phone_code' => 70,'id' => 185,'continent_code' => 'AS','continent_name' => 'Asia'),
            'RW' => array('country_name' => 'Rwanda','phone_code' => 250,'id' => 186,'continent_code' => 'AF','continent_name' => 'Africa'),
            'BL' => array('country_name' => 'Saint Barthelemy','phone_code' => 590,'id' => 187,'continent_code' => 'NA','continent_name' => 'North America'),
            'SH' => array('country_name' => 'Saint Helena','phone_code' => 290,'id' => 188,'continent_code' => 'AF','continent_name' => 'Africa'),
            'KN' => array('country_name' => 'Saint Kitts and Nevis','phone_code' => 1869,'id' => 189,'continent_code' => 'NA','continent_name' => 'North America'),
            'LC' => array('country_name' => 'Saint Lucia','phone_code' => 1758,'id' => 190,'continent_code' => 'NA','continent_name' => 'North America'),
            'MF' => array('country_name' => 'Saint Martin','phone_code' => 590,'id' => 191,'continent_code' => 'NA','continent_name' => 'North America'),
            'PM' => array('country_name' => 'Saint Pierre and Miquelon','phone_code' => 508,'id' => 192,'continent_code' => 'NA','continent_name' => 'North America'),
            'VC' => array('country_name' => 'Saint Vincent and the Grenadines','phone_code' => 1784,'id' => 193,'continent_code' => 'NA','continent_name' => 'North America'),
            'WS' => array('country_name' => 'Samoa','phone_code' => 684,'id' => 194,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'SM' => array('country_name' => 'San Marino','phone_code' => 378,'id' => 195,'continent_code' => 'EU','continent_name' => 'Europe'),
            'ST' => array('country_name' => 'Sao Tome and Principe','phone_code' => 239,'id' => 196,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SA' => array('country_name' => 'Saudi Arabia','phone_code' => 966,'id' => 197,'continent_code' => 'AS','continent_name' => 'Asia'),
            'SN' => array('country_name' => 'Senegal','phone_code' => 221,'id' => 198,'continent_code' => 'AF','continent_name' => 'Africa'),
            'RS' => array('country_name' => 'Serbia','phone_code' => 381,'id' => 199,'continent_code' => 'EU','continent_name' => 'Europe'),
            'CS' => array('country_name' => 'Serbia and Montenegro','phone_code' => 381,'id' => 200,'continent_code' => 'EU','continent_name' => 'Europe'),
            'SC' => array('country_name' => 'Seychelles','phone_code' => 248,'id' => 201,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SL' => array('country_name' => 'Sierra Leone','phone_code' => 232,'id' => 202,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SG' => array('country_name' => 'Singapore','phone_code' => 65,'id' => 203,'continent_code' => 'AS','continent_name' => 'Asia'),
            'SX' => array('country_name' => 'Sint Maarten','phone_code' => 1,'id' => 204,'continent_code' => 'NA','continent_name' => 'North America'),
            'SK' => array('country_name' => 'Slovakia','phone_code' => 421,'id' => 205,'continent_code' => 'EU','continent_name' => 'Europe'),
            'SI' => array('country_name' => 'Slovenia','phone_code' => 386,'id' => 206,'continent_code' => 'EU','continent_name' => 'Europe'),
            'SB' => array('country_name' => 'Solomon Islands','phone_code' => 677,'id' => 207,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'SO' => array('country_name' => 'Somalia','phone_code' => 252,'id' => 208,'continent_code' => 'AF','continent_name' => 'Africa'),
            'ZA' => array('country_name' => 'South Africa','phone_code' => 27,'id' => 209,'continent_code' => 'AF','continent_name' => 'Africa'),
            'GS' => array('country_name' => 'South Georgia and the South Sandwich Islands','phone_code' => 500,'id' => 210,'continent_code' => 'AN','continent_name' => 'Antarctica'),
            'SS' => array('country_name' => 'South Sudan','phone_code' => 211,'id' => 211,'continent_code' => 'AF','continent_name' => 'Africa'),
            'ES' => array('country_name' => 'Spain','phone_code' => 34,'id' => 212,'continent_code' => 'EU','continent_name' => 'Europe'),
            'LK' => array('country_name' => 'Sri Lanka','phone_code' => 94,'id' => 213,'continent_code' => 'AS','continent_name' => 'Asia'),
            'SD' => array('country_name' => 'Sudan','phone_code' => 249,'id' => 214,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SR' => array('country_name' => 'Suriname','phone_code' => 597,'id' => 215,'continent_code' => 'SA','continent_name' => 'South America'),
            'SJ' => array('country_name' => 'Svalbard and Jan Mayen','phone_code' => 47,'id' => 216,'continent_code' => 'EU','continent_name' => 'Europe'),
            'SZ' => array('country_name' => 'Swaziland','phone_code' => 268,'id' => 217,'continent_code' => 'AF','continent_name' => 'Africa'),
            'SE' => array('country_name' => 'Sweden','phone_code' => 46,'id' => 218,'continent_code' => 'EU','continent_name' => 'Europe'),
            'CH' => array('country_name' => 'Switzerland','phone_code' => 41,'id' => 219,'continent_code' => 'EU','continent_name' => 'Europe'),
            'SY' => array('country_name' => 'Syrian Arab Republic','phone_code' => 963,'id' => 220,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TW' => array('country_name' => 'Taiwan, Province of China','phone_code' => 886,'id' => 221,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TJ' => array('country_name' => 'Tajikistan','phone_code' => 992,'id' => 222,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TZ' => array('country_name' => 'Tanzania, United Republic of','phone_code' => 255,'id' => 223,'continent_code' => 'AF','continent_name' => 'Africa'),
            'TH' => array('country_name' => 'Thailand','phone_code' => 66,'id' => 224,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TL' => array('country_name' => 'Timor-Leste','phone_code' => 670,'id' => 225,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TG' => array('country_name' => 'Togo','phone_code' => 228,'id' => 226,'continent_code' => 'AF','continent_name' => 'Africa'),
            'TK' => array('country_name' => 'Tokelau','phone_code' => 690,'id' => 227,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'TO' => array('country_name' => 'Tonga','phone_code' => 676,'id' => 228,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'TT' => array('country_name' => 'Trinidad and Tobago','phone_code' => 1868,'id' => 229,'continent_code' => 'NA','continent_name' => 'North America'),
            'TN' => array('country_name' => 'Tunisia','phone_code' => 216,'id' => 230,'continent_code' => 'AF','continent_name' => 'Africa'),
            'TR' => array('country_name' => 'Turkey','phone_code' => 90,'id' => 231,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TM' => array('country_name' => 'Turkmenistan','phone_code' => 7370,'id' => 232,'continent_code' => 'AS','continent_name' => 'Asia'),
            'TC' => array('country_name' => 'Turks and Caicos Islands','phone_code' => 1649,'id' => 233,'continent_code' => 'NA','continent_name' => 'North America'),
            'TV' => array('country_name' => 'Tuvalu','phone_code' => 688,'id' => 234,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'UG' => array('country_name' => 'Uganda','phone_code' => 256,'id' => 235,'continent_code' => 'AF','continent_name' => 'Africa'),
            'UA' => array('country_name' => 'Ukraine','phone_code' => 380,'id' => 236,'continent_code' => 'EU','continent_name' => 'Europe'),
            'AE' => array('country_name' => 'United Arab Emirates','phone_code' => 971,'id' => 237,'continent_code' => 'AS','continent_name' => 'Asia'),
            'GB' => array('country_name' => 'United Kingdom','phone_code' => 44,'id' => 238,'continent_code' => 'EU','continent_name' => 'Europe'),
            'US' => array('country_name' => 'United States','phone_code' => 1,'id' => 239,'continent_code' => 'NA','continent_name' => 'North America'),
            'UM' => array('country_name' => 'United States Minor Outlying Islands','phone_code' => 1,'id' => 240,'continent_code' => 'NA','continent_name' => 'North America'),
            'UY' => array('country_name' => 'Uruguay','phone_code' => 598,'id' => 241,'continent_code' => 'SA','continent_name' => 'South America'),
            'UZ' => array('country_name' => 'Uzbekistan','phone_code' => 998,'id' => 242,'continent_code' => 'AS','continent_name' => 'Asia'),
            'VU' => array('country_name' => 'Vanuatu','phone_code' => 678,'id' => 243,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'VE' => array('country_name' => 'Venezuela','phone_code' => 58,'id' => 244,'continent_code' => 'SA','continent_name' => 'South America'),
            'VN' => array('country_name' => 'Viet Nam','phone_code' => 84,'id' => 245,'continent_code' => 'AS','continent_name' => 'Asia'),
            'VG' => array('country_name' => 'Virgin Islands, British','phone_code' => 1284,'id' => 246,'continent_code' => 'NA','continent_name' => 'North America'),
            'VI' => array('country_name' => 'Virgin Islands, U.s.','phone_code' => 1340,'id' => 247,'continent_code' => 'NA','continent_name' => 'North America'),
            'WF' => array('country_name' => 'Wallis and Futuna','phone_code' => 681,'id' => 248,'continent_code' => 'OC','continent_name' => 'Oceania'),
            'EH' => array('country_name' => 'Western Sahara','phone_code' => 212,'id' => 249,'continent_code' => 'AF','continent_name' => 'Africa'),
            'YE' => array('country_name' => 'Yemen','phone_code' => 967,'id' => 250,'continent_code' => 'AS','continent_name' => 'Asia'),
            'ZM' => array('country_name' => 'Zambia','phone_code' => 260,'id' => 251,'continent_code' => 'AF','continent_name' => 'Africa'),
            'ZW' => array('country_name' => 'Zimbabwe','phone_code' => 263,'id' => 252,'continent_code' => 'AF','continent_name' => 'Africa')
        );
        foreach ($countries as $key => $val){
            $data=array(
                "name" => $val["country_name"],
                "code" => $val["phone_code"],
                "continent_code" => $val["continent_code"],
                "continent_name" => $val["continent_name"],
            );
            Country::insert($data);
        }
    }
}
